name: UPDATE-NEWS

on:
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:
  
env:
    TELEGRAM: ${{ secrets.TELEGRAM }}
    CHAT_ID: ${{ secrets.CHAT_ID }}
    PST_KEY: ${{ secrets.PST_KEY }}
    PST_KEY_SECRET: ${{ secrets.PST_KEY_SECRET }}
    PST_TOKEN: ${{ secrets.PST_TOKEN }}
    PST_TOKEN_SECRET: ${{ secrets.PST_TOKEN_SECRET }}

jobs:
  Update-news:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ascete
        if: always()
        run:  ./ascete.ps1
        
      - name: Naturae
        if: always()
        run:  ./naturae.ps1
        
      - name: Antarea
        if: always()
        run:  ./antarea.ps1
        
      - name: Zoom-Nature
        if: always()
        run:  ./zoom-nature.ps1
        
      - name: Martinia
        if: always()
        run:  ./martinia.ps1
        
      #- name: INPN
        #if: always()
        #run:  ./inpn.ps1
        
      - name: UICN-FR
        if: always()
        run:  ./uicnfr.ps1
        
      - name: Faune-France
        if: always()
        run:  ./faune-france.ps1
        
      - name: La Pie Bavarde
        if: always()
        run:  ./lapiebavarde.ps1
        
      - name: CRBPO
        if: always()
        run:  ./crbpoinfo.ps1
        
      - name: SHF
        if: always()
        run:  ./shf.ps1
        
      - name: Ornithomedia
        if: always()
        run:  ./ornithomedia.ps1
        
      - name: Oiseaux de France
        if: always()
        run:  ./odf.ps1
        
      - name: VigiNature
        if: always()
        run:  ./viginature.ps1